# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-18 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_technologies'),
    ]

    operations = [
        migrations.CreateModel(
            name='colors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colors', models.CharField(max_length=100)),
            ],
        ),
    ]
