# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-01 09:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='screenshot1',
        ),
        migrations.RemoveField(
            model_name='project',
            name='screenshot2',
        ),
        migrations.RemoveField(
            model_name='project',
            name='screenshot3',
        ),
        migrations.RemoveField(
            model_name='project',
            name='screenshot4',
        ),
    ]
